### ISSUE TITLE
Implement "Submit this post again" link.

### ISSUE THREAD

**Issue by Kerrick** [Kerrick/Mostly-Harmless#20]
I'll need to implement the link in the `Popup.createListHTML()` function. When clicked, it should invoke `Popup.createSubmitForm()`.

I'll also need to detect whether the URL was already submitted to the chosen subreddit. First I'll check the cached data, and use that. If that passes and the URL is submitted, but reddit responds that the link was already submitted to that subreddit, I'll also need to handle that. (That should only pop up if the link was submitted between the time the data was fetched from the API and cached, and the time of the attempted submission.)

**Comment by Kerrick** [comment]
Should it append the form to the list of posts, or clear the list away and show only the form?

/cc @JH1

**Comment by JH1** [comment]
I think it should append. The list is still important info.

**Comment by Kerrick** [comment]
Well, there could always be a "go back to the list" option if it didn't append it. And, if the popup closes, it'll _always_ re-open with the list. Still think append?

**Comment by JH1** [comment]
Not really clear now. Would the user get the info of what other subs the link is in right off the bat? That would be a good thing I think.

**Comment by Kerrick** [comment]
I'll spell out the two ways I can see this being implemented. I personally prefer Method 1.

### Both Methods
1. The user opens a page
2. Mostly Harmless figures out that the page has been submitted at least one time.
3. Mostly Harmless shows a number on its icon
4. The user clicks the Mostly Harmless icon
5. The popup shows a list of the submitted posts (like it does now)
6. At the bottom of the list is a link to submit the post again

### Method 1

7. When the user clicks on the submit again link, the popup clears out and shows just the submit form, with a link to go back to the list of submitted posts.

8. If the user closes the popup without submitting the post, and opens the popup again, go back to step 5.

9. If the user clicks the link to go back to the list of submitted posts, go back to step 5.

### Method 2

7. When the user clicks on the link to submit the post again, the submit form replaces the submit link, but the list of submitted posts stays above the submit form.

8. If the user closes the popup without submitting the post, go back to step 5.

**Comment by JH1** [comment]
Okay I see what you mean now. Yeah method 1 would be completely fine.
