### ISSUE TITLE
Not displaying "click to see link"

### ISSUE THREAD

**Issue by JH1** [Kerrick/Mostly-Harmless#27]
Recently extension has started  stalling before displaying the 'click to see submitted link' link. If I check afterwards, the link has still gone through though.

I've tried uninstalling and reinstalling the extension, but it didn't help. I'm currently using 18.0.1025.162 m

**Comment by Kerrick** [comment]
I can confirm that this happens. After you submit a link, it seems to be pending indefinitely, but it actually does submit the link.

**Comment by JH1** [comment]
Seems like a recent glitch, within the last week or two.
