### ISSUE TITLE
Requesting field expansion

### ISSUE THREAD

**Issue by JH1** [Kerrick/Mostly-Harmless#29]
Ability to expand fields

**Comment by Kerrick** [comment]
How do you mean?

**Comment by JH1** [comment]
Like on Reddit itself, where you can grab a corner of a text submission field and drag to expand. Not sure if this would work, but thought I'd toss it in there. Would be handy on occasion.

**Comment by Kerrick** [comment]
Hmm... I'll play around with it, but I don't know how it'd work being in a popup. Since the popup's height is determined by the height of its elements, it might do weird things to the popup if you resize something vertically. Leaving as pending.
