### ISSUE TITLE
Better "popular choices" section on submit form

### ISSUE THREAD

**Issue by JH1** [Kerrick/Mostly-Harmless#31]
A popular choices section that's based on submission history through Mostly Harmless. At the moment it seems random.

**Comment by Kerrick** [comment]
Actually, it's based on your subscribed subreddits, just like the official reddit.com submit page! :)

**Comment by JH1** [comment]
Yeah that makes sense. At this point it's about as useful as that too. ;'P

**Comment by Kerrick** [comment]
I've opened a new related feature request to hopefully make it more useful. #33
