### ISSUE TITLE
Irrelevant content/URLs...

### ISSUE THREAD

**Issue by McNerdius** [Kerrick/Mostly-Harmless#4]
Not sure how this would be categorized - but i think some sort of "What you're looking at is totally inapplicable to this extension" functionality, similar to the '+' and '#' indicators.  In particular, when i'm on Gmail or my google docs whatnot, it still shows that one or more have submitted this page to reddit.  Well, clearly not, AND, there's no way or reason to do so.

Sorry if this isn't descriptive enough... Honestly though, it's the only thing that sticks out to me so far.

**Comment by Kerrick** [comment]
Thanks for submitting the issue! I am going to handle this by allowing users to exclude certain domains (and regex patterns) from being looked up. In fact, I've fixed this in commit [1aeac5f](https://github.com/Kerrick/Mostly-Harmless/commit/1aeac5fee00cbcb4d875c95beba13f60434b9bbd) (based on [Issue 2](https://github.com/Kerrick/Mostly-Harmless/issues/2)), and it will be rolling out shortly. :)

Here's how looks:

![screenshot](http://kerrick.github.com/Mostly-Harmless/images/ss_excludedDomains.png)
