### ISSUE TITLE
Feature/Possible Bug:  Check orangereds.

### ISSUE THREAD

**Issue by McNerdius** [Kerrick/Mostly-Harmless#6]
I don't know why it would be: but i do know one thing - on more than one occasion, i'd have been messing on the computer in the morning for an hour or so (no orangered notifications), then after a bit, say i want to watch something on youtube, i may have to restart chrome (lately it's been audio driver issues [ubuntu] which force me to logout/login till i find a better solution) and when chrome starts back up - i'm hit with an orangered notification.

Perhaps a right-click menu option to manually recheck orangereds would be in order ?  (if that's possible...)

**Comment by Kerrick** [comment]
Mostly Harmless only checks that you have unread mail, not what mail comes in. It also checks at your specified interval, regardless of whether or not it has alerted you. The result of this is that if you don't actually read the orangered, Mostly Harmless _should_ indefinitely notify you at your specified interval.

Could you please test this by waiting at least for the interval before visiting your inbox when you have unread mail and telling me if you get another notification? To make this easier, try going to the options page, hitting F12, opening the Console, and typing `new Store('settings').set('mailInterval','0.5');` to change the interval to 30 seconds -- slide it back to 5 minutes when you're done.

If you do not get notified multiple times, this is a bug. If you do, Mostly Harmless is behaving as expected. Either way, we can explore additional options:
1. I could make the slider for the notification display time go higher than 60 seconds.
2. I could add a checkbox to make the notification persistent until one of the following happens:
   1. You click the notification to open your inbox
   2. You click the X on the notification to close it manually
   3. Mostly Harmless checks your inbox, and you have no orangereds
