### ISSUE TITLE
Dozens of info.json requests are sent upon activation with "wait for click."

### ISSUE THREAD

**Issue by Kerrick** [Kerrick/Mostly-Harmless#7]
It seems that when the user has "Wait for click" activated, and then clicks the browser action to load info about the page, dozens of HTTP requests are sent one after another to `http://www.reddit.com/api/info.json` until the first one response. I'm not sure what's causing this, but it **needs to be fixed ASAP**, as this is a **MAJOR** problem.

[Screenshot](http://i.imgur.com/7FiHE.png)

**Comment by chromakode** [comment]
This isn't hitting us too hard yet, but it's definitely something that should be fixed ASAP.

**Comment by Kerrick** [comment]
Luckily it's only when people have "wait for click" enabled and then click the icon, so that'll give me the couple hours needed to figure out what the heck is going on. :S

**Comment by Kerrick** [comment]
It may have something to do with the way I handle getting info. Normally, I call `background.prepareBrowserAction()`, which does a few checks and then calls `reddit.getInfo()`. However, if the browser action icon is in the ignore state, I simply call `reddit.getInfo()` on click.

The only thing I'm doing in `background.prepareBrowserAction()` that isn't a check whether to call `button.setBadgeIgnore()` is this, starting on line 839:

``` javascript
                if (cache.get(tab.url) === undefined || cache.get(tab.url).cacheDate - utils.epoch() < -60  * settings.get('cacheTime')) {
                    console.log(chrome.i18n.getMessage('loading_api'));
                    reddit.getInfo(tab.url, tabId);
                } else {
                    console.log(chrome.i18n.getMessage('loading_cache'));
                    button.setBadgeFor(tab.url, tabId);
                }
```

It's quite possible that, if I'm not running that cache check, it could keep looking to the API until it is cached. I'll do some fiddling around once I get back to my desktop with my dev environment and find out.

**Comment by Kerrick** [comment]
When you use `browserAction.onClicked.addListener` more than once, the calls stack, which is why it was calling `reddit.getInfo` so many times. Now I only `addListener` when I `setBadgeDefaults`, because simply removing the popup allows `handleManualClick` to run. I'll push to the Chrome Web Store momentarily.
